spring:
  profiles:
    active: dve
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-BRAND-SERVICE
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou
      username: root
      password: root
  profiles: dve
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis-plus:
  mapper-locations: classpath:cn/seanjian/haigou/mapper/*Mapper.xml
type-aliases-package: cn.seanjian.haigou.domain
---
server:
  port: 8004
spring:
  application:
    name: PRODUCT-BRAND-SERVICE-TEST
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou
      username: root
      password: root
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis-plus:
  mapper-locations: classpath:cn/seanjian/haigou/mapper/*Mapper.xml
type-aliases-package: cn.seanjian.haigou.domain
