spring:
  profiles:
    active:
    - dve
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-BRAND-SERVICE
  datasource:
      url: jdbc:mysql://localhost:3306/haigou
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  profiles: dve
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
mybatis-plus:
  mapper-locations: cn/seanjian/mybatisplus/mapper/*Mapper.xml
  type-aliases-package: cn.seanjian.mybatisplus.domain #设置別名
---
server:
  port: 8004
spring:
  application:
    name: PRODUCT-BRAND-SERVICE-TEST
  datasource:
      url: jdbc:mysql://localhost:3306/haigou
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
mybatis-plus:
  mapper-locations:cn/seanjian/haigou/mapper/*Mapper.xml
  type-aliases-package: cn.seanjian.haigou.domain #设置別名