spring:
  profiles:
    active: dve
---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: dve
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: plat-service
    plat.path: /plat/**
    product.serviceId: product-brand-service
    product.path: /product/**
    common.serviceId: common-privoder
    common.path: /common/**
  ignored-services: "*"
  prefix: "/haigou"
---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9528.com 
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: plat-service-test
    plat.path: /plat/**
    product.serviceId: product-brand-service-test
    product.path: /product/**
    common.serviceId: common-privoder
    common.path: /common/**
  ignored-services: "*"
  prefix: "/haigou"